language: java

dist: xenial

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL

after_success:
  - bash <(curl -s https://codecov.io/bash)